_core:
  default_config_hash: 7LkiviGITIpniIOOIzpuxR7r4XzqqYN_cwu0fb0kx1M
content_access_roles_gids:
  anonymous: 1
  authenticated: 2
  content_editor: 3
  administrator: 4
  agent: 5
  musician: 6
content_access_node_type:
  page: 'a:3:{s:8:"view_own";a:3:{i:0;s:9:"anonymous";i:1;s:13:"authenticated";i:2;s:13:"administrator";}s:4:"view";a:3:{i:0;s:9:"anonymous";i:1;s:13:"authenticated";i:2;s:13:"administrator";}s:8:"per_node";i:1;}'
  booking: 'a:2:{s:8:"view_own";a:2:{i:0;s:13:"authenticated";i:1;s:13:"administrator";}s:4:"view";a:2:{i:0;s:13:"authenticated";i:1;s:13:"administrator";}}'
  contact: 'a:2:{s:8:"view_own";a:2:{i:0;s:13:"authenticated";i:1;s:13:"administrator";}s:4:"view";a:2:{i:0;s:13:"authenticated";i:1;s:13:"administrator";}}'
  musician: 'a:2:{s:8:"view_own";a:2:{i:0;s:13:"authenticated";i:1;s:13:"administrator";}s:4:"view";a:2:{i:0;s:13:"authenticated";i:1;s:13:"administrator";}}'
